default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: qwicksync_development

test:
  <<: *default
  database: qwicksync_test


production:
  <<: *default
  database: qwicksync_production
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
